// <auto-generated />
using System;
using MemoryMuseum.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MemoryMuseum.Migrations
{
    [DbContext(typeof(MemoryMuseumDbContext))]
    partial class MemoryMuseumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MemoryMuseum.Models.Exhibit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Exhibits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hall of Games",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hall of Dog Toys",
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hall of Dog Stuff I Found",
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hall of Noodles",
                            UserProfileId = 4
                        });
                });

            modelBuilder.Entity("MemoryMuseum.Models.ExhibitRating", b =>
                {
                    b.Property<int>("ExhibitId")
                        .HasColumnType("integer");

                    b.Property<int>("RatingId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("ExhibitId", "RatingId", "UserProfileId");

                    b.HasIndex("RatingId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ExhibitRatings");
                });

            modelBuilder.Entity("MemoryMuseum.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExhibitId")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NeedsApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("Placard")
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExhibitId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Approved = true,
                            DatePublished = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ExhibitId = 1,
                            Image = "/images/gameandwatch.jpg",
                            Name = "Game and Watch",
                            NeedsApproval = false,
                            Placard = "Although this was made back in 2020, this machine mimics those built in the 1980s. This one is Mario themed and contains the game ball, as well as Super Mario Bros, and Super Mario Bros. 2(Lost Levels) They didn't have that back then!",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Approved = true,
                            DatePublished = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ExhibitId = 1,
                            Image = "/images/nintendods.jpg",
                            Name = "Nintendo DS",
                            NeedsApproval = false,
                            Placard = "First Released in 2004, this one has wear and tear on it, literally. The screen has been worn. During some of the best years in gaming this device has seen better days.",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            Approved = true,
                            DatePublished = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ExhibitId = 2,
                            Image = "/images/woodywoodpecker.jpg",
                            Name = "Woody Woodpecker toy",
                            NeedsApproval = false,
                            Placard = "This is my favorite toy in life. Woody the Woodpecker. Jayme actually bought me three of these this is the third one. He does his trade mark laugh drives me mad.",
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 4,
                            Approved = true,
                            DatePublished = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ExhibitId = 2,
                            Image = "/images/pyroraptortoy.jpg",
                            Name = "Pyro Raptor Toy",
                            NeedsApproval = false,
                            Placard = "From that Jurrassic movie I never saw. I really loved this toy. So I am putting it here on display for you all. Please do not squeak it.",
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 5,
                            Approved = true,
                            DatePublished = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ExhibitId = 3,
                            Image = "/images/darkdoorway.jpg",
                            Name = "Hidden Doorway",
                            NeedsApproval = false,
                            Placard = "This creepy door has a bunch of cool stuff. I get my exhibit items here",
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 6,
                            Approved = true,
                            DatePublished = new DateTime(2024, 6, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ExhibitId = 3,
                            Image = "/images/gumbyplay.jpg",
                            Name = "Gumby Toy",
                            NeedsApproval = false,
                            Placard = "I am pretty sure this is Gumby.",
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 7,
                            Approved = true,
                            DatePublished = new DateTime(2024, 8, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ExhibitId = 4,
                            Image = "/images/chung.png",
                            Name = "Big Chungus",
                            NeedsApproval = false,
                            Placard = "I am pretty sure this is Bugs Bunny.",
                            UserProfileId = 4
                        },
                        new
                        {
                            Id = 8,
                            Approved = true,
                            DatePublished = new DateTime(2024, 8, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ExhibitId = 4,
                            Image = "/images/turkey.jpg",
                            Name = "A Turkey",
                            NeedsApproval = false,
                            Placard = "I am pretty sure this is a turkey.",
                            UserProfileId = 5
                        },
                        new
                        {
                            Id = 9,
                            Approved = true,
                            DatePublished = new DateTime(2024, 8, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ExhibitId = 4,
                            Image = "/images/beads.jpg",
                            Name = "A Turkey",
                            NeedsApproval = false,
                            Placard = "I am pretty sure this is beads.",
                            UserProfileId = 3
                        });
                });

            modelBuilder.Entity("MemoryMuseum.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RatingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RatingName = "Needs work",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            RatingName = "Could be better",
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            RatingName = "Okay",
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            RatingName = "Good",
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            RatingName = "Awesome",
                            Value = 5
                        });
                });

            modelBuilder.Entity("MemoryMuseum.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean");

                    b.Property<int>("ReportAuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportSubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportAuthorId");

                    b.HasIndex("ReportSubjectId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Fox is a good boy",
                            Closed = true,
                            ReportAuthorId = 1,
                            ReportSubjectId = 3
                        });
                });

            modelBuilder.Entity("MemoryMuseum.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AdminApproved")
                        .HasColumnType("boolean");

                    b.Property<int?>("AdminApprovedId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "101 Dalmations",
                            AdminApproved = false,
                            AdminApprovedId = 0,
                            CreateDateTime = new DateTime(2024, 1, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jayme",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            IsActive = true,
                            LastName = "Chaka"
                        },
                        new
                        {
                            Id = 2,
                            Address = "101 Dalmations",
                            AdminApproved = false,
                            AdminApprovedId = 0,
                            CreateDateTime = new DateTime(2024, 1, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kaya",
                            IdentityUserId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            IsActive = true,
                            LastName = "Chaka"
                        },
                        new
                        {
                            Id = 3,
                            Address = "101 Dalmations",
                            AdminApproved = false,
                            AdminApprovedId = 0,
                            CreateDateTime = new DateTime(2024, 6, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fox",
                            IdentityUserId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            IsActive = true,
                            LastName = "Gaba"
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Ramen Way",
                            AdminApproved = false,
                            AdminApprovedId = 0,
                            CreateDateTime = new DateTime(2024, 8, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bongo",
                            IdentityUserId = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            IsActive = false,
                            LastName = "Chaka"
                        },
                        new
                        {
                            Id = 5,
                            Address = "101 Bell Blvd",
                            AdminApproved = false,
                            AdminApprovedId = 0,
                            CreateDateTime = new DateTime(2024, 8, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jerry",
                            IdentityUserId = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            IsActive = false,
                            LastName = "Chaka"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            Name = "Admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea601200-c2a7-4422-8aec-65b9e3c9f544",
                            Email = "jayme@chaka.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKms7OV6l7TKsplZsRgA4Rw+ICJO3I0Ep5ImgSr/ij1HqN8yb0m+XZuFrVcYRuxBpw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2c18643d-7eb2-4268-a820-716adf569863",
                            TwoFactorEnabled = false,
                            UserName = "JaymeChaka"
                        },
                        new
                        {
                            Id = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "77d3f359-deef-410f-9625-a46669aa12f3",
                            Email = "kaya@gaba.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAECojyyRKaoSx0tWVM2+8K2p9iqJiIZ7Hg6eDribm7P0jwkNtwWWc9ciN15rBA6Qaww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db84a049-b0e9-48aa-850b-b45f2141ae44",
                            TwoFactorEnabled = false,
                            UserName = "KayaGaba"
                        },
                        new
                        {
                            Id = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9f762e9d-16aa-4cc2-a2b1-7c1a9dd88e8d",
                            Email = "fox@gaba.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBwANDJ7zrVWkLmhF20jUIDKXj/HmZlh2CW7frl3SHlUK2cjANAO1zWoCe+i8hfbjQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ece56a21-e3a8-4933-8e88-500f9d5bee38",
                            TwoFactorEnabled = false,
                            UserName = "FoxGaba"
                        },
                        new
                        {
                            Id = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aeb130b8-a7d1-43eb-9235-254fde29fc27",
                            Email = "bongo@gaba.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEN1Q2JJW5sFahRHMk2WoJm9ITsUTrWdcWFDar2qQkyCEzOphPuAE1UVkYxPn2NDwuw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "48fe53fe-b20a-45fb-a8f3-7582ae2bcf3f",
                            TwoFactorEnabled = false,
                            UserName = "BongoGaba"
                        },
                        new
                        {
                            Id = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "779004b6-4243-42f3-ba05-929d22e6e7fb",
                            Email = "jerry@gaba.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEF13uVi/cEB922B1Ohd22CBB1hzkt8wsId0KCNdGfjjvJsGQqv9/9dgMTgA7Orcimw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31e522b6-c49a-4a8c-8baf-fae9100be89f",
                            TwoFactorEnabled = false,
                            UserName = "JerryGaba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        },
                        new
                        {
                            UserId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        },
                        new
                        {
                            UserId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MemoryMuseum.Models.Exhibit", b =>
                {
                    b.HasOne("MemoryMuseum.Models.UserProfile", "UserProfile")
                        .WithMany("Exhibits")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MemoryMuseum.Models.ExhibitRating", b =>
                {
                    b.HasOne("MemoryMuseum.Models.Exhibit", "Exhibit")
                        .WithMany("ExhibitRatings")
                        .HasForeignKey("ExhibitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoryMuseum.Models.Rating", "Rating")
                        .WithMany("ExhibitRatings")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoryMuseum.Models.UserProfile", "UserProfile")
                        .WithMany("ExhibitRatings")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exhibit");

                    b.Navigation("Rating");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MemoryMuseum.Models.Item", b =>
                {
                    b.HasOne("MemoryMuseum.Models.Exhibit", "Exhibit")
                        .WithMany("Items")
                        .HasForeignKey("ExhibitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoryMuseum.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exhibit");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MemoryMuseum.Models.Report", b =>
                {
                    b.HasOne("MemoryMuseum.Models.UserProfile", "ReportAuthor")
                        .WithMany()
                        .HasForeignKey("ReportAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoryMuseum.Models.UserProfile", "ReportSubject")
                        .WithMany()
                        .HasForeignKey("ReportSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportAuthor");

                    b.Navigation("ReportSubject");
                });

            modelBuilder.Entity("MemoryMuseum.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemoryMuseum.Models.Exhibit", b =>
                {
                    b.Navigation("ExhibitRatings");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MemoryMuseum.Models.Rating", b =>
                {
                    b.Navigation("ExhibitRatings");
                });

            modelBuilder.Entity("MemoryMuseum.Models.UserProfile", b =>
                {
                    b.Navigation("ExhibitRatings");

                    b.Navigation("Exhibits");
                });
#pragma warning restore 612, 618
        }
    }
}
